library identifier: 'gx-library'

pipeline {
    agent { node { label 'kbbuilder-node-6' } }
    stages {
        stage('Setup parameters') {
            steps {
                script { 
                    properties([
                        parameters([
                            booleanParam(defaultValue: false, description: 'Force rebuild', name: 'forceRebuild'),
                            booleanParam(defaultValue: false, description: 'Force update GeneXus Installation', name: 'forceUpdateGX')
                        ]),
                        disableConcurrentBuilds(),
                        buildDiscarder(logRotator(numToKeepStr: '10'))
                    ])
                }
            }
        }
        stage('Configure GeneXus Installation') {
            steps {
                jobHandleGeneXusInstallation params.forceUpdateGX
            }
        }
        stage('Checkout/Update KnowledgeBase') {
            steps {
                jobUpdateKnowledgeBase params.forceUpdateGX
            }
        }
        /*
        stage('Process Reorganization') {
            steps {
                jobHandleGeneXusInstallation "Calling handle gx instalaltion"
            }
        }
        stage('Build KnowledgeBase') {
            steps {
                jobHandleGeneXusInstallation "Calling handle gx instalaltion"
            }
        }
        stage('Execute Unit Tests') {
            steps {
                jobHandleGeneXusInstallation "Calling handle gx instalaltion"
            }
        }
        */
    }
}